### ISSUE TITLE
HI!  with esp8266  in linux mint and windows to have this issues, any recomendation ? tks!

### ISSUE THREAD

**Issue by ghost** [siara-cc/esp_arduino_sqlite3_lib#26]
home/ricardo/Arduino/libraries/esp_arduino_sqlite3_lib-master/src/sdfat_fns.cpp:51:5: error: 'File' was not declared in this scope; did you mean 'SdFile'?
   51 |     File file = sdFats[sd_idx]->open(name + 5, imode);

**Comment by siara-cc** [comment]
Hi, have you installed the dependent SDFat library? https://github.com/siara-cc/esp_arduino_sqlite3_lib#dependencies--pre-requisites

**Comment by infality** [comment]
I ran into the same problem with the latest SdFat version (2.2.2) but was able to successfully compile with version 2.0.1.
All SdFat versions after 2.0.1 do not work with this library

EDIT: Just saw the note that we should use version 1.0.7
